### ISSUE TITLE
Improve the developer guide

### ISSUE THREAD

**Issue by myyerrol** [microdynamics/microdynamics_developer_guide#1]
I have finished the **microdynamics_developer_guide**. @maksyuki You should read these carefully and make your suggestions to improve the developer guide. After we determine the final version, I will export files into pdf format. So, please read and check these guide as soon as you can!

**Comment by maksyuki** [comment]
Ok.

**Comment by maksyuki** [comment]
I will submit bugs using **pull requests**.

**Comment by myyerrol** [comment]
OK!!!
